name: Ingmar Vroege
favicon: null
layout_spectrum: 0.9578
typography_spectrum: 0.83037
title: Ingmar Vroege
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef3f7'
    - '#000002'
    - '#8d6645'
    - '#96b052'
    - '#503022'
  brandStrength: 0.875
  lightness: 0.8162714887876064
  saturation: 0.7781360414810479
  rhythmicContrast: 0.8499481116887182
purpose: []
