name: Ingmar Vroege
favicon: null
layout_spectrum: 0.8017252371646464
typography_spectrum: 0.8380822925828397
title: Ingmar Vroege
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3448147785384208
  lightness: 0.8162714887876064
  saturation: 0.7781360414810479
  rhythmicContrast: 0.8499481116887182
purpose: []
