name: Ingmar Vroege
favicon: null
layout_spectrum: 0.39133
typography_spectrum: 0.83037
title: Ingmar Vroege
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef3f7'
    - '#000002'
    - '#8d6645'
    - '#96b052'
    - '#503022'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
